### ISSUE TITLE
Switching from CUPS to p910nd

### ISSUE THREAD

**Issue by MegaZeroX10** [kenyapcomau/p910nd#3]
How do I do that?

**Comment by kenyapcomau** [comment]
Outside scope of project. It's not a replacement, it can only substitute for part of the function of a remote CUPS daemon.

**Comment by MegaZeroX10** [comment]
What do you mean?

**Comment by kenyapcomau** [comment]
The original intent of p910nd was to be used on diskless clients. Subsequently it was also adopted by router distros like dd-wrt and openwrt for connecting a printer to the USB port if the router had one. For other use cases you're better off installing a full featured daemon like cupsd.

I should also note there that p910nd is not an active project. It hasn't been touched since 2014. I also don't have a use for it personally. The object of moving it from Sourceforge to Github is so that contributing can be easier. For example I know there are maintainers for downstream distros like Debian that have written packaging and init scripts. Github is a place they can submit those distro-specific pieces. Also if somebody wants to add Bonjour support.
