### ISSUE TITLE
Issue with printing via it

### ISSUE THREAD

**Issue by MegaZeroX10** [kenyapcomau/p910nd#4]
I cannot print a test page via Windows 7 to a printer that is connected to the Raspberry Pi running it. The log that is shown when using the -d parameter is as follows:

pi@raspberrypi:~/p910nd $ sudo ./p910nd -f /dev/bus/usb/001/004 -d
Connection from 10.0.1.3 port 55001 accepted
read 1460 bytes from network
write: Invalid argument
Finished job: 0/1460 bytes sent to printer
copy_stream: Invalid argument

The output of lsusb is as follows:

Bus 001 Device 004: ID 03f0:1d17 HP, Inc LaserJet 1320
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by kenyapcomau** [comment]
Raspberry Pi runs Debian. You'd be better off installing the Debian ARM architecture package for p910nd. Otherwise if symptoms persist hopefully somebody can point out why.

**Comment by MegaZeroX10** [comment]
I built it from its source code.

**Comment by kenyapcomau** [comment]
You should run the cups service and it that works, stick with it. Maybe somebody will figure out what p910nd is missing and contribute that.

**Comment by MegaZeroX10** [comment]
People have been able to run it on Raspberry Pi devices.

**Comment by kenyapcomau** [comment]
Sorry I don't have any experience running it on RPi. A RPi forum might be more helpful.

**Comment by MegaZeroX10** [comment]
I tried using the version available from the repository. Nothing is displayed when i use the -d parameter.

**Comment by MegaZeroX10** [comment]
How did you get it installed? Maybe you can remote into my PC to see if you can get it working.

**Comment by MegaZeroX10** [comment]
I see there are instructions on https://www.raspberrypi.org/forums/viewtopic.php?t=22498 but they seem complicated. Also, the usblp driver that is linked to in them is no longer available.

**Comment by MegaZeroX10** [comment]
I figured it out. I just had to run modprobe usblp and change the config file to use /dev/usb/lp0 instead of the default (which is /dev/lp0). It should try using /dev/lpx and /dev/usb/lpx (where x is the number of the printer).

**Comment by kenyapcomau** [comment]
That's what the -f option is for, to specify an alternate printer device. Usually people use -f /dev/usb/lpX or -f /dev/usblpX instead of the /dev/bus entry. It might then autoload the USB driver, I can't say. The printer number is then for distinct instances and ports. Probably the -f should be made mandatory instead of defaulting to /dev/lpX which is historical and from the days of parallel printer ports, but that would be a restriction of features for no good reason. I don't see a good reason for autodetecting printer ports, it's apt to get the wrong one, but if somebody can make a good case for it AND write the code AND test it, I'll consider accepting a pull request. Note that in many cases you might want to use port 9100 (hence printer 0) even though your printer might be at /dev/usblp1. This can already be specified with -f. So autodetection should probably be made part of a configuration utility. Again if somebody wants to contribute that...

Anyway good that you got it working.
